---

GENERAL:
  experience_logs:
    save: True
    load: False
    path: Reports/Logs/text_log_analysis

  conversation_logs:
    save: True
    nlp: True
    load: False
    path: Reports/Conversations/text_conversation_analysis

DIALOGUE:
  num_dialogues: 1

  domain: Movie

  ontology_path: simulation/bot/jmrs1/Data/movies-rules.json
  db_path: simulation/bot/jmrs1/Data/movies-dbase.db

AGENT_0:
  role: system

  DM:
    policy:
      type: handcrafted

    nlu: movie
    nlg: movie


  NLU:
    nlu: movie

  DST:
    dst: movie

  NLG:
    nlg: movie

